[build-system]
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "raptor"
version = "0.1.0"
license = "BSD-3-Clause"
license-files = ["LICENSE"]
authors = [
  { name="John Coleman", email="colemanjs@ornl.gov" },
  { name="Vamsi Subraveti", email="vamsi.r.subraveti@vanderbilt.edu" }
]
description = "A library to predict porosity in Laser Powder Bed Fusion (LPBF) builds."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "numpy",
    "numba",
    "psutil",
    "scipy",
    "matplotlib",
    "PyYAML",
    "vtk",
    "scikit-image",
    "pandas",
    "pyvista",
    "intersect-sdk",
    "dial @ git+https://github.com/INTERSECT-DIAL/dial@sable",
    "sable @ git+https://code.ornl.gov/sable/sable@develop",
]

[project.optional-dependencies]
test = [
    "pytest",
]
dev = [
    "build",
    "pre-commit",
]

[project.scripts]
raptor = "raptor.cli:run"
raptor-warm-cache = "raptor.warmup:run"

[project.urls]
Homepage = "https://github.com/ORNL-MDF/Raptor"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.black]
line-length = 80
