#!/bin/sh
cd ${0%/*} || exit 1

cd melt_pool_model
python create_melt_pool_model.py --config ../local_config/local-conf.json

cd ../defect_model
python create_defect_model.py --config ../local_config/local-conf.json
python plot_defect_model.py
