name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  run:
    name: Run Raptor
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Run example
        run: |
          base=$(pwd)
          cd $base/examples/cli_example
          NUMBA_NUM_THREADS=2 raptor input.yaml
          
          cd $base/examples/api_example
          NUMBA_NUM_THREADS=2 python rve.py
