name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${ {github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Create venv and install dependencies
        run: |
          echo "Creating a virtual environment..."
          python -m venv venv
          echo "Activating the virtual environment and installing the project..."
          source venv/bin/activate
          pip install .
      - name: Upload venv artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-venv
          path: venv/

  run:
    name: Run Raptor
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download venv artifact
        uses: actions/download-artifact@v4
        with:
          name: python-venv
          path: venv/
      - name: Run application
        run: |
          echo "Activating the virtual environment..."
          chmod +x venv/bin/*
          source venv/bin/activate

          echo "Changing to the examples directory..."
          cd examples

          echo "Running the main application..."
          raptor input.yaml
